package ScanPicture;

import Libraries.XImage;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.border.LineBorder;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.videoio.Videoio;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nguyen Duy Minh
 */
public class VideoCapture extends javax.swing.JDialog {

    /**
     * Creates new form VideoCapture
     */
    public DeamonThread myThread = null;
    public org.opencv.videoio.VideoCapture webSource = null;
    public Mat frame = new Mat();
    public MatOfByte mem = new MatOfByte();
    public Graphics g;
    public String nameImg = "image";
    
    class DeamonThread implements Runnable {
        
        protected volatile boolean runnable = false;
        
        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    if (webSource.grab()) {
                        try {
                            webSource.retrieve(frame);
                            //định dạng ảnh khi vẽ lên jpanell
                            Imgcodecs.imencode(".jpg", frame, mem);
                            //ảnh của webcam là một array
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                            BufferedImage buff = (BufferedImage) im;
                            g = jPanel1.getGraphics();
                            //vẽ chuỗi ảnh của webcam vào jpanell
                            if (g.drawImage(buff, 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    this.wait();
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Error");
                        }
                    }
                }
            }
        }
    }
    
    public void setFormat(String namefile, String loai) {
        this.nameImg = namefile;
        if (loai.equalsIgnoreCase("Products")) {
            SaveFile = new JFileChooser("D:\\IDE\\Git\\DuAn1\\ManagePhoneStore\\Images\\Products");
        } else {
            SaveFile = new JFileChooser("D:\\IDE\\Git\\DuAn1\\ManagePhoneStore\\Images\\RecognitionFace");
        }        
    }
    
    public VideoCapture(java.awt.Frame parent, boolean modal, String a, String b) {
        super(parent, modal);
        this.setTitle("Chụp ảnh");
        this.setIconImage(XImage.getIcon("chupanh.png"));
        initComponents();
        setLocationRelativeTo(this);
        btnPause.setEnabled(false);
        btnScan.setEnabled(false);
        if (!a.equals("") && !b.equals("")) {
            setFormat(a, b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        SaveFile = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btnStar = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnScan = new javax.swing.JButton();
        jPanel1.setBorder(new LineBorder(Color.BLACK, 1, true));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 450, Short.MAX_VALUE)
        );
        
        btnStar.setText("Bật Camera");
        btnStar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStarActionPerformed(evt);
            }
        });
        
        btnPause.setText("Dừng Hình");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        
        btnScan.setText("Chụp ảnh");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                                        .addComponent(btnStar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnStar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)
                                                .addComponent(btnScan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)
                                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStarActionPerformed
        //bật webcam
        webSource = new org.opencv.videoio.VideoCapture(0, Videoio.CAP_DSHOW);
        myThread = new DeamonThread();
        Thread t = new Thread(myThread);
        myThread.runnable = true;
        t.start();
        btnStar.setEnabled(false);
        btnPause.setEnabled(true);
        btnScan.setEnabled(true);
    }//GEN-LAST:event_btnStarActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        //dừng webcam
        myThread.runnable = false;
        btnStar.setEnabled(true);
        btnPause.setEnabled(false);
        btnScan.setEnabled(false);
        webSource.release();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        //dừng webcam xong chụp ảnh lưu ảnh vào bộ nhớ máy
        myThread.runnable = false;
        btnStar.setEnabled(true);
        btnPause.setEnabled(false);
        btnScan.setEnabled(false);
        webSource.release();
        SaveFile.setSelectedFile(new File(nameImg + ".jpg"));
        int returnval = SaveFile.showSaveDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            File file = SaveFile.getSelectedFile();
            org.opencv.imgcodecs.Imgcodecs.imwrite(file.getAbsolutePath(), frame);
        } else {
            System.out.println("File access cancelled by user.");
        }
        
    }//GEN-LAST:event_btnScanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VideoCapture dialog = new VideoCapture(new javax.swing.JFrame(), true,"none","none");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStar;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnScan;
    private javax.swing.JFileChooser SaveFile;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
