/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFarme;

import Libraries.Dialog;
import Libraries.Login;
import javax.swing.ImageIcon;
/**
 *
 * @author PC
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Manage
     */
    public Employee() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nen = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        Thanhtruot = new javax.swing.JScrollPane();
        txtMassage = new javax.swing.JTextArea();
        Thanhcongcu = new javax.swing.JToolBar();
        btnView_phone = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnImprotCoupon = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        mnuAccout = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniChangePassword = new javax.swing.JMenuItem();
        mniBack = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniInformationPhone = new javax.swing.JMenuItem();
        mniInfomationCustomer = new javax.swing.JMenuItem();
        mniOrder = new javax.swing.JMenuItem();
        mniImportCoupon = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mniStorePhone = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniUserManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee");
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(getClass().getResource("/Image/Icon/Logo.jpg")).getImage());

        nen.setBackground(new java.awt.Color(204, 255, 255));

        lbltitle.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lbltitle.setText("Message");

        txtMassage.setEditable(false);
        txtMassage.setColumns(20);
        txtMassage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMassage.setLineWrap(true);
        txtMassage.setRows(5);
        txtMassage.setText("Quy định của cửa hàng:\n- Nhân viên mặc đúng đồng phục\n- Cư xử và hành động đúng mực với khách hàng và đồng nghiệp\n- Nghiêm cấm các hành vi gian trá lừa gạt\n- Nghiêm túc trong công việc\n- Báo cáo với bộ phận IT ngay khi có lỗi với hệ thống, không được tự tiện xử lí");
        txtMassage.setWrapStyleWord(true);
        Thanhtruot.setViewportView(txtMassage);

        Thanhcongcu.setRollover(true);
        Thanhcongcu.setPreferredSize(new java.awt.Dimension(639, 50));

        btnView_phone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnView_phone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/dienthoai.png"))); // NOI18N
        btnView_phone.setText("View - Phone");
        btnView_phone.setFocusable(false);
        btnView_phone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView_phone.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnView_phone.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_phoneActionPerformed(evt);
            }
        });
        Thanhcongcu.add(btnView_phone);

        btnOrder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/order.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setFocusable(false);
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        Thanhcongcu.add(btnOrder);

        btnCustomer.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/customer.png"))); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.setFocusable(false);
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        Thanhcongcu.add(btnCustomer);

        btnImprotCoupon.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnImprotCoupon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/ImportCoupon.png"))); // NOI18N
        btnImprotCoupon.setText("Import Coupon");
        btnImprotCoupon.setFocusable(false);
        btnImprotCoupon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprotCoupon.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnImprotCoupon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprotCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprotCouponActionPerformed(evt);
            }
        });
        Thanhcongcu.add(btnImprotCoupon);

        javax.swing.GroupLayout nenLayout = new javax.swing.GroupLayout(nen);
        nen.setLayout(nenLayout);
        nenLayout.setHorizontalGroup(
            nenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
            .addGroup(nenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nenLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Thanhtruot, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55))
                .addGroup(nenLayout.createSequentialGroup()
                    .addGap(485, 485, 485)
                    .addComponent(lbltitle)
                    .addGap(507, 507, Short.MAX_VALUE))
                .addComponent(Thanhcongcu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE))
        );
        nenLayout.setVerticalGroup(
            nenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(nenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nenLayout.createSequentialGroup()
                    .addComponent(Thanhcongcu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Thanhtruot, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        mnuAccout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/accout.png"))); // NOI18N
        mnuAccout.setText("Accout");
        mnuAccout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuAccout.setMargin(new java.awt.Insets(5, 10, 5, 10));

        mniLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLogin.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/login_1.png"))); // NOI18N
        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuAccout.add(mniLogin);

        mniLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLogout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/logout.png"))); // NOI18N
        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuAccout.add(mniLogout);

        mniChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniChangePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/ChangePassword.png"))); // NOI18N
        mniChangePassword.setText("Change Password");
        mniChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePasswordActionPerformed(evt);
            }
        });
        mnuAccout.add(mniChangePassword);

        mniBack.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniBack.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Exit.png"))); // NOI18N
        mniBack.setText("Exit");
        mniBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBackActionPerformed(evt);
            }
        });
        mnuAccout.add(mniBack);

        Menu.add(mnuAccout);

        mnuManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/manage01.png"))); // NOI18N
        mnuManage.setText("Manage");
        mnuManage.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuManage.setMargin(new java.awt.Insets(5, 10, 5, 10));

        mniInformationPhone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniInformationPhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniInformationPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/dienthoai.png"))); // NOI18N
        mniInformationPhone.setText("Information Phone");
        mniInformationPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInformationPhoneActionPerformed(evt);
            }
        });
        mnuManage.add(mniInformationPhone);

        mniInfomationCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniInfomationCustomer.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniInfomationCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/customer.png"))); // NOI18N
        mniInfomationCustomer.setText("Information Customer");
        mniInfomationCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInfomationCustomerActionPerformed(evt);
            }
        });
        mnuManage.add(mniInfomationCustomer);

        mniOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniOrder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/order.png"))); // NOI18N
        mniOrder.setText("Order");
        mniOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOrderActionPerformed(evt);
            }
        });
        mnuManage.add(mniOrder);

        mniImportCoupon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniImportCoupon.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniImportCoupon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/ImportCoupon.png"))); // NOI18N
        mniImportCoupon.setText("Import Coupon");
        mniImportCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniImportCouponActionPerformed(evt);
            }
        });
        mnuManage.add(mniImportCoupon);

        Menu.add(mnuManage);

        mnuView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/view.png"))); // NOI18N
        mnuView.setText("View");
        mnuView.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuView.setMargin(new java.awt.Insets(5, 10, 5, 10));

        mniStorePhone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniStorePhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniStorePhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/StorePhone.png"))); // NOI18N
        mniStorePhone.setText("Store Phone");
        mniStorePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStorePhoneActionPerformed(evt);
            }
        });
        mnuView.add(mniStorePhone);

        Menu.add(mnuView);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/help.png"))); // NOI18N
        mnuHelp.setText("Help");
        mnuHelp.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuHelp.setMargin(new java.awt.Insets(5, 10, 5, 10));

        mniUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniUserManual.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mniUserManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/UserManual.png"))); // NOI18N
        mniUserManual.setText("User Manual");
        mniUserManual.setToolTipText("");
        mnuHelp.add(mniUserManual);

        Menu.add(mnuHelp);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        openLogout();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniInfomationCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInfomationCustomerActionPerformed
        openInformationCustomer();
    }//GEN-LAST:event_mniInfomationCustomerActionPerformed

    private void mniChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePasswordActionPerformed
        changPassword();
    }//GEN-LAST:event_mniChangePasswordActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        openLogin();
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniInformationPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInformationPhoneActionPerformed
        openInformationPhone();
    }//GEN-LAST:event_mniInformationPhoneActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        openOrder();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnView_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_phoneActionPerformed
        openViewPhone();
    }//GEN-LAST:event_btnView_phoneActionPerformed

    private void mniImportCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniImportCouponActionPerformed
        openImportCoupon();
    }//GEN-LAST:event_mniImportCouponActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        openInformationCustomer();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void mniStorePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStorePhoneActionPerformed
        openViewPhone();
    }//GEN-LAST:event_mniStorePhoneActionPerformed

    private void btnImprotCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprotCouponActionPerformed
        openImportCoupon();
    }//GEN-LAST:event_btnImprotCouponActionPerformed

    private void mniOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOrderActionPerformed
        openOrder();
    }//GEN-LAST:event_mniOrderActionPerformed

    private void mniBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBackActionPerformed
        if (Dialog.Confirm(this, "Bạn chắc chắn thoát chứ !"))
            System.exit(0);
    }//GEN-LAST:event_mniBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JToolBar Thanhcongcu;
    private javax.swing.JScrollPane Thanhtruot;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnImprotCoupon;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnView_phone;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JMenuItem mniBack;
    private javax.swing.JMenuItem mniChangePassword;
    private javax.swing.JMenuItem mniImportCoupon;
    private javax.swing.JMenuItem mniInfomationCustomer;
    private javax.swing.JMenuItem mniInformationPhone;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniOrder;
    private javax.swing.JMenuItem mniStorePhone;
    private javax.swing.JMenuItem mniUserManual;
    private javax.swing.JMenu mnuAccout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuView;
    private javax.swing.JPanel nen;
    private javax.swing.JTextArea txtMassage;
    // End of variables declaration//GEN-END:variables
private void init() {
        this.setLocationRelativeTo(null);
    }

    void openLogin() {
        try {
            if (Login.user != null) {
                Dialog.MessageInformation(this, "Vui lòng đăng xuất !");
            } else {
                this.dispose();
                new FormLogin().setVisible(true);
            }
        } catch (Exception e) {
        }
    }

    void openLogout() {
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Vui lòng đăng xuất trước khi đăng nhập");
            } else {
                Login.clear();
                this.dispose();
                new FormLogin().setVisible(true);
            }
        } catch (Exception e) {
        }
    }

    void changPassword() {
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Vui lòng đăng nhập để đổi mật khẩu!");
            } else {
                new ChangePassword(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }

    void back() {
        try {

        } catch (Exception e) {
        }
    }

    void openInformationPhone() {
        try {
            new ManagePhone(this, true).setVisible(true);
        } catch (Exception e) {
        }
    }

    void openInformationCustomer() {
        try {
            new ManageCustomer(this, true).setVisible(true);
        } catch (Exception e) {
        }
    }

    void openOrder() {
        try {
            new ManageOrder(this, true).setVisible(true);
        } catch (Exception e) {
        }
    }

    void openImportCoupon() {
        try {
            new ManageImport(this, true).setVisible(true);
        } catch (Exception e) {
        }
    }

    void openViewPhone() {
        try {
            new StorePhone(this, true).setVisible(true);
        } catch (Exception e) {
        }
    }

    void userManual() {
        try {

        } catch (Exception e) {
        }
    }
}
