/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFarme;

import ConnectSQLSever.ConnectSQLSever;
import Entity.InformationUsers;
import Libraries.Dialog;
import Libraries.Login;
import Libraries.XImage;
import ScanPicture.LoginQR;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author NguyenMinhHau_PS24488
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    private String mabaomatU,
            /**
             * Creates new form FormLogin
             */
            mabaomatA;

    public FormLogin() {
        new Loading(this, true).setVisible(true);
        initComponents();
        setLayout();
        init();
    }

    public void init() {
        setLocationRelativeTo(null);
        mabaomatU = macapchaUser();
        mabaomatA = macapchaAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nen = new javax.swing.JPanel();
        tieude = new javax.swing.JLabel();
        Thongtin = new javax.swing.JLabel();
        LVR = new javax.swing.JTabbedPane();
        dangnhapU = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtUserNameEmployee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPasswordsEmployee = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        macapuser = new javax.swing.JLabel();
        txtmabaomatE = new javax.swing.JTextField();
        btnloginE = new javax.swing.JButton();
        btncancelE = new javax.swing.JButton();
        btnloginQR = new javax.swing.JButton();
        dangnhapM = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPasswordsManager = new javax.swing.JPasswordField();
        txtUserNameManager = new javax.swing.JTextField();
        btnloginM = new javax.swing.JButton();
        btncanelM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        macapadmin = new javax.swing.JLabel();
        txtmabaomatM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(153, 153, 255));
        setIconImage(new ImageIcon(getClass().getResource("/Image/Icon/login.png")).getImage());
        setSize(new java.awt.Dimension(600, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Nen.setBackground(new java.awt.Color(230, 230, 255));

        tieude.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        tieude.setForeground(new java.awt.Color(153, 102, 255));
        tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieude.setText("Login");

        Thongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/login1.png"))); // NOI18N
        Thongtin.setAlignmentX(1.0F);
        Thongtin.setAlignmentY(1.0F);
        Thongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongtinMouseClicked(evt);
            }
        });

        LVR.setBackground(new java.awt.Color(204, 204, 255));
        LVR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));
        LVR.setForeground(new java.awt.Color(102, 153, 255));
        LVR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LVR.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N

        dangnhapU.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel7.setText("UsersName");

        txtUserNameEmployee.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        txtUserNameEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameEmployeeActionPerformed(evt);
            }
        });
        txtUserNameEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameEmployeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameEmployeeKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel8.setText("Passwords");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel4.setText("Code protection");

        txtmabaomatE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        txtmabaomatE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmabaomatEActionPerformed(evt);
            }
        });
        txtmabaomatE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmabaomatEKeyPressed(evt);
            }
        });

        btnloginE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnloginE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/login_1.png"))); // NOI18N
        btnloginE.setText("Login");
        btnloginE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginEActionPerformed(evt);
            }
        });

        btncancelE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btncancelE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Cancel_1.png"))); // NOI18N
        btncancelE.setText("Cancel");
        btncancelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelEActionPerformed(evt);
            }
        });

        btnloginQR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnloginQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/QR.png"))); // NOI18N
        btnloginQR.setText("QR Code");
        btnloginQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dangnhapULayout = new javax.swing.GroupLayout(dangnhapU);
        dangnhapU.setLayout(dangnhapULayout);
        dangnhapULayout.setHorizontalGroup(
            dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapULayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloginQR))
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dangnhapULayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmabaomatE)
                            .addComponent(txtUserNameEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordsEmployee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(macapuser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(dangnhapULayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnloginE)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dangnhapULayout.setVerticalGroup(
            dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapULayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordsEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macapuser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmabaomatE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(dangnhapULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloginE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloginQR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        LVR.addTab("  Employee  ", dangnhapU);

        dangnhapM.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel5.setText("AdminName");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel6.setText("Passwords");

        txtPasswordsManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordsManagerActionPerformed(evt);
            }
        });

        txtUserNameManager.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        txtUserNameManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameManagerActionPerformed(evt);
            }
        });

        btnloginM.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnloginM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/login_1.png"))); // NOI18N
        btnloginM.setText("Login");
        btnloginM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginMActionPerformed(evt);
            }
        });

        btncanelM.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btncanelM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Cancel_1.png"))); // NOI18N
        btncanelM.setText("Cancel");
        btncanelM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanelMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel3.setText("Code protection");

        txtmabaomatM.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        txtmabaomatM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmabaomatMKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dangnhapMLayout = new javax.swing.GroupLayout(dangnhapM);
        dangnhapM.setLayout(dangnhapMLayout);
        dangnhapMLayout.setHorizontalGroup(
            dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapMLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtmabaomatM)
                    .addComponent(txtUserNameManager, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasswordsManager, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(macapadmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dangnhapMLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnloginM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncanelM)
                .addGap(55, 55, 55))
        );
        dangnhapMLayout.setVerticalGroup(
            dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapMLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserNameManager, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macapadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmabaomatM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(dangnhapMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnloginM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncanelM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        LVR.addTab("  Manager  ", dangnhapM);

        javax.swing.GroupLayout NenLayout = new javax.swing.GroupLayout(Nen);
        Nen.setLayout(NenLayout);
        NenLayout.setHorizontalGroup(
            NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NenLayout.createSequentialGroup()
                .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Thongtin)
                        .addGap(18, 18, 18)
                        .addComponent(LVR, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NenLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        NenLayout.setVerticalGroup(
            NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieude)
                .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LVR, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NenLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Thongtin)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameManagerActionPerformed

    private void btnloginMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginMActionPerformed
        try {
            loginManager();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnloginMActionPerformed

    private void btncanelMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanelMActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "You definitely want to escape ! ", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btncanelMActionPerformed

    private void txtUserNameEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameEmployeeActionPerformed

    private void btnloginEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginEActionPerformed
        try {
            loginEmployee();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnloginEActionPerformed

    private void btncancelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelEActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "You definitely want to escape ! ", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btncancelEActionPerformed

    private void txtUserNameEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameEmployeeKeyReleased

    }//GEN-LAST:event_txtUserNameEmployeeKeyReleased

    private void txtUserNameEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameEmployeeKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            showRemember();
//        }
    }//GEN-LAST:event_txtUserNameEmployeeKeyPressed

    private void txtmabaomatEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmabaomatEActionPerformed

    }//GEN-LAST:event_txtmabaomatEActionPerformed

    private void txtmabaomatEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmabaomatEKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                loginEmployee();
            } catch (Exception ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtmabaomatEKeyPressed

    private void txtmabaomatMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmabaomatMKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                loginManager();
            } catch (Exception ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtmabaomatMKeyPressed

    private void ThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongtinMouseClicked
        JOptionPane.showMessageDialog(null, "Name : Login\nLast Update : 09/11/2022\nVersion : 1.0.0");
    }//GEN-LAST:event_ThongtinMouseClicked

    private void txtPasswordsManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordsManagerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPasswordsManagerActionPerformed

    private void btnloginQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginQRActionPerformed
        // TODO add your handling code here:
        try {
            LoginQR QR = new LoginQR(null, true);
            QR.setVisible(true);
            if (Login.user != null) {
                Dialog.MessageInformation(this, "Logged in successfully");
            } else {
                Dialog.MessageError(this, "The account information is not correct, please check again");
            }
        } catch (Exception e) {
            Dialog.MessageError(null, String.valueOf(e));
        }
    }//GEN-LAST:event_btnloginQRActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane LVR;
    private javax.swing.JPanel Nen;
    private javax.swing.JLabel Thongtin;
    private javax.swing.JButton btncancelE;
    private javax.swing.JButton btncanelM;
    private javax.swing.JButton btnloginE;
    private javax.swing.JButton btnloginM;
    private javax.swing.JButton btnloginQR;
    private javax.swing.JPanel dangnhapM;
    private javax.swing.JPanel dangnhapU;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel macapadmin;
    private javax.swing.JLabel macapuser;
    private javax.swing.JLabel tieude;
    private javax.swing.JPasswordField txtPasswordsEmployee;
    private javax.swing.JPasswordField txtPasswordsManager;
    private javax.swing.JTextField txtUserNameEmployee;
    private javax.swing.JTextField txtUserNameManager;
    private javax.swing.JTextField txtmabaomatE;
    private javax.swing.JTextField txtmabaomatM;
    // End of variables declaration//GEN-END:variables
 void setLayout() {
        LVR.setUI(new BasicTabbedPaneUI());
        LVR.setForeground(new Color(50, 100, 200));
        LVR.addMouseListener(new MouseAdapter() {

//            @Override
//            public void mouseEntered(MouseEvent e) {
//                LVR.setBackground(new Color(244, 157, 26));
//                LVR.setBorder(new LineBorder(new Color(240, 240, 240), 1));
//            }
//            @Override
//            public void mouseExited(MouseEvent e) {
//              LVR.setForeground(new Color(200, 100, 200));
//                LVR.setBorder(new LineBorder(new Color(239, 245, 245), 1));
//            }
        });

    }

    private void loginManager() throws Exception {
        try {

            if (checkNullM()) {
                if (txtmabaomatM.getText().equalsIgnoreCase(mabaomatA)) {
                    InformationUsers u = new InformationUsers();
                    u.setUserName(txtUserNameManager.getText());
                    u.setPassWords(txtPasswordsManager.getText());
                    u.setRoles(true);
                    if (u.checkLoginAdmin()) {
                        Dialog.MessageInformation(null, "Logged in successfully");
                        Login.user = u;
                        new Manager().setVisible(true);
                        this.dispose();
                    } else {
                        Dialog.MessageWarning(null, "The account information is not correct, please check again");
                    }
                } else {
                    Dialog.MessageWarning(null, "Security code is incorrect");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void loginEmployee() throws Exception {
        try {
            if (checkNullE()) {
                if (txtmabaomatE.getText().equalsIgnoreCase(mabaomatU)) {
                    InformationUsers u = new InformationUsers();
                    u.setUserName(txtUserNameEmployee.getText());
                    u.setPassWords(txtPasswordsEmployee.getText());
                    u.setRoles(false);
                    if (u.checkLoginUser()) {
                        Dialog.MessageInformation(null, "Logged in successfully");
                        Login.user = u;
                        new Employee().setVisible(true);
                        this.dispose();
                    } else {
                        Dialog.MessageWarning(null, "The account information is not correct, please check again");
                    }
                } else {
                    Dialog.MessageWarning(null, "Security code is incorrect");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

//    public void showRemember() {
//        try {
//            ConnectSQLSever con = new ConnectSQLSever();
//            Connection connect = con.getConnection();
//            ResultSet rs = con.getTable("Remember");
//            while (rs.next()) {
//                if (txtUserNameEmployee.getText().equals(rs.getString(2))) {
//                    txtPasswordsEmployee.setText(rs.getString(3));
//                    txtmabaomatE.requestFocus();
//                    remember.setSelected(true);
//                    return;
//                }
//            }
//            txtPasswordsEmployee.requestFocus();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }

    public boolean checkNullM() {
        if (txtUserNameManager.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtUserNameManager.requestFocus();
            return false;
        } else if (txtPasswordsManager.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "PPassword cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtPasswordsManager.requestFocus();
            return false;
        } else if (txtmabaomatM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Security code cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtmabaomatM.requestFocus();
            return false;
        }
        return true;
    }

    public boolean checkNullE() {
        if (txtUserNameEmployee.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtUserNameEmployee.requestFocus();
            return false;
        } else if (txtPasswordsEmployee.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtPasswordsEmployee.requestFocus();
            return false;
        } else if (txtmabaomatE.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Security code cannot be empty", "Login error", JOptionPane.ERROR_MESSAGE);
            txtmabaomatE.requestFocus();
            return false;
        }
        return true;
    }

    public String macapchaAdmin() {
        int k = (int) ((Math.random()) * 6) + 1;
        String f = null;
        XImage XI = new XImage();
        if (k == 1) {
            macapadmin.setIcon(XI.setIconToSize("cap1.png", 260, 45, 0));
            f = "morning";
        } else if (k == 2) {
            macapadmin.setIcon(XI.setIconToSize("cap2.png", 260, 45, 0));
            f = "caPtChA";
        } else if (k == 3) {
            macapadmin.setIcon(XI.setIconToSize("cap3.png", 260, 45, 0));
            f = "Thrand";
        } else if (k == 4) {
            macapadmin.setIcon(XI.setIconToSize("cap4.png", 260, 45, 0));
            f = "8M5MnMp2";
        } else if (k == 5) {
            macapadmin.setIcon(XI.setIconToSize("cap5.png", 260, 45, 0));
            f = "Iamhum@n";
        } else if (k == 6) {
            macapadmin.setIcon(XI.setIconToSize("cap6.png", 260, 45, 0));
            f = "plvwy2";
        }
        return f;
    }

    public String macapchaUser() {
        int k = (int) ((Math.random()) * 6) + 1;
        String f = null;
        XImage XI = new XImage();
        if (k == 1) {
            macapuser.setIcon(XI.setIconToSize("cap1.png", 260, 45, 0));
            f = "morning";
        } else if (k == 2) {
            macapuser.setIcon(XI.setIconToSize("cap2.png", 260, 45, 0));
            f = "caPtChA";
        } else if (k == 3) {
            macapuser.setIcon(XI.setIconToSize("cap3.png", 260, 45, 0));
            f = "Thrand";
        } else if (k == 4) {
            macapuser.setIcon(XI.setIconToSize("cap4.png", 260, 45, 0));
            f = "8M5MnMp2";
        } else if (k == 5) {
            macapuser.setIcon(XI.setIconToSize("cap5.png", 260, 45, 0));
            f = "Iamhum@n";
        } else if (k == 6) {
            macapuser.setIcon(XI.setIconToSize("cap6.png", 260, 45, 0));
            f = "plvwy2";
        }
        return f;
    }
    /// xử lí đăng nhập

}
