/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFarme;

import Libraries.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author Dell
 */
public class Loading extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Loading(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(this);
        lblogo.setIcon(XImage.setResizeable(new ImageIcon(getClass().getResource("/Image/Icon/Logo.jpg")), 300, 300, 0));
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = pgbLoad.getValue();
                if (x < pgbLoad.getMaximum()) {
                    pgbLoad.setValue(x + 1);
                } else {
                    Loading.this.dispose();
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nen = new javax.swing.JPanel();
        lblLoad = new javax.swing.JLabel();
        lblWait = new javax.swing.JLabel();
        pgbLoad = new javax.swing.JProgressBar();
        lblogo = new javax.swing.JLabel();

        setTitle("Loading");
        setIconImage(new ImageIcon(getClass().getResource("/Image/Icon/login.png")).getImage());

        Nen.setBackground(new java.awt.Color(255, 204, 204));

        lblLoad.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblLoad.setText("Loading...");

        lblWait.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblWait.setText("Please feel free to wait forever !");

        pgbLoad.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        pgbLoad.setToolTipText("");
        pgbLoad.setName("\n"); // NOI18N
        pgbLoad.setStringPainted(true);

        lblogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout NenLayout = new javax.swing.GroupLayout(Nen);
        Nen.setLayout(NenLayout);
        NenLayout.setHorizontalGroup(
            NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pgbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NenLayout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NenLayout.createSequentialGroup()
                                    .addComponent(lblLoad)
                                    .addGap(296, 296, 296))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NenLayout.createSequentialGroup()
                                    .addComponent(lblWait)
                                    .addGap(210, 210, 210)))))
                    .addContainerGap()))
        );
        NenLayout.setVerticalGroup(
            NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(NenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblLoad)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblWait)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pgbLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Nen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Nen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Loading dialog = new Loading(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nen;
    private javax.swing.JLabel lblLoad;
    private javax.swing.JLabel lblWait;
    private javax.swing.JLabel lblogo;
    private javax.swing.JProgressBar pgbLoad;
    // End of variables declaration//GEN-END:variables
}
