/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to showDetail this template
 */
package MainFarme;

import javax.swing.ImageIcon;
import DAO.InformationUserDAO;
import Entity.InformationUsers;
import Libraries.Dialog;
import Libraries.Login;
import Libraries.XDate;
import Libraries.XImage;
import ScanPicture.VideoCapture;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicLabelUI;
import javax.swing.plaf.basic.BasicPanelUI;
import javax.swing.plaf.basic.BasicScrollPaneUI;
import javax.swing.plaf.basic.BasicSeparatorUI;
import javax.swing.plaf.basic.BasicTableUI;
import javax.swing.plaf.basic.BasicTextFieldUI;
import javax.swing.plaf.basic.BasicToolBarUI;
import javax.swing.table.DefaultTableModel;
import org.opencv.core.Core;

/**
 *
 * @author PC
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    InformationUserDAO dao = new InformationUserDAO();
    public int row;

    public Manager() {
        initComponents();
        setLayout();
        init();
    }

    public void init() {
        setLocationRelativeTo(this);
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        this.fillTable();
        this.row = -1;
        this.updateStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        tlbmanager = new javax.swing.JToolBar();
        btnmanagePhone = new javax.swing.JButton();
        btnKPI = new javax.swing.JButton();
        btnTurnover = new javax.swing.JButton();
        btnDebt = new javax.swing.JButton();
        spll = new javax.swing.JToolBar.Separator();
        btnLogout = new javax.swing.JButton();
        lblinfor = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        lblcodeEmpoloyee = new javax.swing.JLabel();
        lblFind = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtCodeEmployee = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnScan = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        SPTable = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCanel = new javax.swing.JButton();
        btnLeftEnd = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnRightEnd = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        DataBirth = new com.toedter.calendar.JDateChooser();
        rdoemployye = new javax.swing.JRadioButton();
        rdomanager = new javax.swing.JRadioButton();
        mnumanager = new javax.swing.JMenuBar();
        mnuAccout = new javax.swing.JMenu();
        mItemLogin = new javax.swing.JMenuItem();
        mItemLogout = new javax.swing.JMenuItem();
        mItemChangePass = new javax.swing.JMenuItem();
        mitemBack = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mItemInforPhone = new javax.swing.JMenuItem();
        mItemInforCustomer = new javax.swing.JMenuItem();
        mItemOrder = new javax.swing.JMenuItem();
        mItemImport = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mItemStorePhone = new javax.swing.JMenuItem();
        mnuStatistical = new javax.swing.JMenu();
        mItemTurnover = new javax.swing.JMenuItem();
        mItemDebt = new javax.swing.JMenuItem();
        spt = new javax.swing.JPopupMenu.Separator();
        mItemKDI = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mItemUse = new javax.swing.JMenuItem();
        mItemAbout = new javax.swing.JMenuItem();
        mItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        setIconImage(new ImageIcon(getClass().getResource("/Image/Icon/Logo.jpg")).getImage());

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        tlbmanager.setBackground(new java.awt.Color(255, 255, 255));
        tlbmanager.setRollover(true);

        btnmanagePhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnmanagePhone.setText("Manage Phone");
        btnmanagePhone.setFocusable(false);
        btnmanagePhone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmanagePhone.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnmanagePhone.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmanagePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagePhoneActionPerformed(evt);
            }
        });
        tlbmanager.add(btnmanagePhone);

        btnKPI.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnKPI.setText("  KPI Product   ");
        btnKPI.setFocusable(false);
        btnKPI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKPI.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnKPI.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKPIActionPerformed(evt);
            }
        });
        tlbmanager.add(btnKPI);

        btnTurnover.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnTurnover.setText("  Turnover  ");
        btnTurnover.setFocusable(false);
        btnTurnover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTurnover.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnTurnover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTurnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoverActionPerformed(evt);
            }
        });
        tlbmanager.add(btnTurnover);

        btnDebt.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnDebt.setText("Debt");
        btnDebt.setFocusable(false);
        btnDebt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDebt.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnDebt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebtActionPerformed(evt);
            }
        });
        tlbmanager.add(btnDebt);
        tlbmanager.add(spll);

        btnLogout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnLogout.setText("  Logout  ");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        tlbmanager.add(btnLogout);

        lblinfor.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblinfor.setText("Infomation Employee");

        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblimage.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimageMouseClicked(evt);
            }
        });

        lblcodeEmpoloyee.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblcodeEmpoloyee.setText("Code Employee:");

        lblFind.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblFind.setText("Find Employee:");

        txtSearch.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Search_1.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtCodeEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeEmployeeActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblYear.setText("Birth Year:");

        lblemail.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblemail.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblname.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblname.setText("Full Name:");

        lblPhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblPhone.setText("Phone Number:");

        lblAddress.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblAddress.setText("Addres:");

        txtFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnScan.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/scan_1.png"))); // NOI18N
        btnScan.setText("Scan");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/upload.png"))); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        tblEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodeName", "FullName", "BirthYear", "PhoneNumber", "Email", "Address"
            }
        ));
        tblEmployee.setRowHeight(20);
        tblEmployee.setRowMargin(2);
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseReleased(evt);
            }
        });
        SPTable.setViewportView(tblEmployee);

        btnInsert.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/insert.png"))); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCanel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Cancel_1.png"))); // NOI18N
        btnCanel.setText("Cancel");
        btnCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanelActionPerformed(evt);
            }
        });

        btnLeftEnd.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnLeftEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/leftend.png"))); // NOI18N
        btnLeftEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftEndActionPerformed(evt);
            }
        });

        btnLeft.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/left.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/next.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnRightEnd.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnRightEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/rightend.png"))); // NOI18N
        btnRightEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightEndActionPerformed(evt);
            }
        });

        image.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        image.setText("Image");

        DataBirth.setDateFormatString("dd/MM/yyyy");
        DataBirth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnG.add(rdoemployye);
        rdoemployye.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdoemployye.setText("Emplooyye");
        rdoemployye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoemployyeActionPerformed(evt);
            }
        });

        btnG.add(rdomanager);
        rdomanager.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdomanager.setText("Manager");
        rdomanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomanagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(image)))
                        .addGap(53, 53, 53)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblcodeEmpoloyee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtCodeEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(DataBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPhone)
                                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(rdomanager)
                                .addGap(28, 28, 28)
                                .addComponent(rdoemployye))))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(btnScan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(SPTable, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addComponent(btnLeftEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnRightEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFind)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoemployye)
                            .addComponent(rdomanager))
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addComponent(lblcodeEmpoloyee)
                                        .addGap(73, 73, 73)
                                        .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelMainLayout.createSequentialGroup()
                                            .addComponent(lblPhone)
                                            .addGap(18, 18, 18)
                                            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblAddress)))
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addComponent(txtCodeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(66, 66, 66)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblname)
                                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYear)))))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnScan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(btnCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SPTable, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLeftEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRightEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        mnumanager.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        mnumanager.setMinimumSize(new java.awt.Dimension(437, 38));
        mnumanager.setPreferredSize(new java.awt.Dimension(437, 38));
        mnumanager.setRequestFocusEnabled(false);
        mnumanager.setVerifyInputWhenFocusTarget(false);

        mnuAccout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/accout.png"))); // NOI18N
        mnuAccout.setText("  Accout  ");
        mnuAccout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuAccout.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuAccout.setMinimumSize(new java.awt.Dimension(87, 35));
        mnuAccout.setName(""); // NOI18N

        mItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mItemLogin.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/login_1.png"))); // NOI18N
        mItemLogin.setText("Login");
        mItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLoginActionPerformed(evt);
            }
        });
        mnuAccout.add(mItemLogin);

        mItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mItemLogout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/logout.png"))); // NOI18N
        mItemLogout.setText("Logout");
        mItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLogoutActionPerformed(evt);
            }
        });
        mnuAccout.add(mItemLogout);

        mItemChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mItemChangePass.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/ChangePassword.png"))); // NOI18N
        mItemChangePass.setText("Change Password");
        mItemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemChangePassActionPerformed(evt);
            }
        });
        mnuAccout.add(mItemChangePass);

        mitemBack.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mitemBack.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mitemBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Exit.png"))); // NOI18N
        mitemBack.setText("Exit");
        mitemBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemBackActionPerformed(evt);
            }
        });
        mnuAccout.add(mitemBack);

        mnumanager.add(mnuAccout);

        mnuManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/manage01.png"))); // NOI18N
        mnuManage.setText("  Manage  ");
        mnuManage.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuManage.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuManage.setName(""); // NOI18N

        mItemInforPhone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemInforPhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemInforPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/dienthoai.png"))); // NOI18N
        mItemInforPhone.setText("Information Phone");
        mItemInforPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemInforPhoneActionPerformed(evt);
            }
        });
        mnuManage.add(mItemInforPhone);

        mItemInforCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemInforCustomer.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemInforCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/customer.png"))); // NOI18N
        mItemInforCustomer.setText("Information Customer");
        mItemInforCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemInforCustomerActionPerformed(evt);
            }
        });
        mnuManage.add(mItemInforCustomer);

        mItemOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemOrder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/order.png"))); // NOI18N
        mItemOrder.setText("Order");
        mItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemOrderActionPerformed(evt);
            }
        });
        mnuManage.add(mItemOrder);

        mItemImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemImport.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/ImportCoupon.png"))); // NOI18N
        mItemImport.setText("Import Coupon");
        mItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemImportActionPerformed(evt);
            }
        });
        mnuManage.add(mItemImport);

        mnumanager.add(mnuManage);

        mnuView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/view.png"))); // NOI18N
        mnuView.setText("  View  ");
        mnuView.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuView.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuView.setName(""); // NOI18N

        mItemStorePhone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        mItemStorePhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemStorePhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/StorePhone.png"))); // NOI18N
        mItemStorePhone.setText("Store Phone");
        mItemStorePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemStorePhoneActionPerformed(evt);
            }
        });
        mnuView.add(mItemStorePhone);

        mnumanager.add(mnuView);

        mnuStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/statistical.png"))); // NOI18N
        mnuStatistical.setText("  Statistical  ");
        mnuStatistical.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuStatistical.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuStatistical.setName(""); // NOI18N

        mItemTurnover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemTurnover.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemTurnover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/TurnOver.png"))); // NOI18N
        mItemTurnover.setText("TurnOver");
        mItemTurnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTurnoverActionPerformed(evt);
            }
        });
        mnuStatistical.add(mItemTurnover);

        mItemDebt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemDebt.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemDebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Debt.png"))); // NOI18N
        mItemDebt.setText("Debt");
        mItemDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDebtActionPerformed(evt);
            }
        });
        mnuStatistical.add(mItemDebt);
        mnuStatistical.add(spt);

        mItemKDI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemKDI.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemKDI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/KDI Employee.png"))); // NOI18N
        mItemKDI.setText("KPI Product");
        mItemKDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemKDIActionPerformed(evt);
            }
        });
        mnuStatistical.add(mItemKDI);

        mnumanager.add(mnuStatistical);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/help.png"))); // NOI18N
        mnuHelp.setText("  Help  ");
        mnuHelp.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mnuHelp.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuHelp.setMinimumSize(new java.awt.Dimension(87, 35));
        mnuHelp.setName(""); // NOI18N

        mItemUse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mItemUse.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemUse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/UserManual.png"))); // NOI18N
        mItemUse.setText("User manual");
        mnuHelp.add(mItemUse);

        mItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mItemAbout.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/about.png"))); // NOI18N
        mItemAbout.setText("About");
        mItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mItemAbout);

        mItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mItemExit.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        mItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Exit.png"))); // NOI18N
        mItemExit.setText("Exit");
        mItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemExitActionPerformed(evt);
            }
        });
        mnuHelp.add(mItemExit);

        mnumanager.add(mnuHelp);

        setJMenuBar(mnumanager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbmanager, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(lblinfor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbmanager, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblinfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagePhoneActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                this.dispose();
                new ManagePhone(this, true).setVisible(true);
            }
        } catch (Exception e) {
            Dialog.MessageError(this, e);
        }
    }//GEN-LAST:event_btnmanagePhoneActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Not logged in!");
            } else {
                if (Dialog.Confirm(this, "Are you sure you want to sign out?")) {
                    this.dispose();
                    new FormLogin().setVisible(true);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtCodeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeEmployeeActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void lblimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimageMouseClicked
        // TODO add your handling code here:
        try {
            getImage();
        } catch (Exception e) {
            Dialog.MessageError(this, "Can't select photo");
        }
    }//GEN-LAST:event_lblimageMouseClicked

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        if (txtCodeEmployee.getText().trim().equals("")) {
            Dialog.MessageWarning(this, "Please enter CodeEmployye to take a picture");
        } else {
            try {
                VideoCapture vd = new VideoCapture(this, true, txtCodeEmployee.getText().trim(), "Face");
                vd.setVisible(true);
            } catch (Exception e) {
                Dialog.MessageError(this, "Can't open camera");
            }
        }
    }//GEN-LAST:event_btnScanActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        try {
            getImage();
        } catch (Exception e) {
            Dialog.MessageError(this, "Can't select photo");
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        Insert();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void mItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemImportActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                new ManageImport(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemImportActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void mItemChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemChangePassActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to change your password!");
            } else {
                new ChangePassword(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemChangePassActionPerformed

    private void mItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLogoutActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Not logged in!");
            } else {
                if (Dialog.Confirm(this, "Are you sure you want to sign out?")) {
                    this.dispose();
                    new FormLogin().setVisible(true);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemLogoutActionPerformed

    private void mItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLoginActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user != null) {
                Dialog.MessageWarning(this, "Please log out before logging in");
            } else {
                Login.clear();
                this.dispose();
                new FormLogin().setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemLoginActionPerformed

    private void mItemInforCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemInforCustomerActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                new ManageCustomer(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemInforCustomerActionPerformed

    private void mItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemAboutActionPerformed

    private void tblEmployeeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblEmployee.getSelectedRow();
            showDetail();
            this.updateStatus();
        }
    }//GEN-LAST:event_tblEmployeeMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageError(this, "Please log in");
            } else {
                if (txtCodeEmployee.getText().equalsIgnoreCase(Login.user.getUserName())) {
                    Dialog.MessageWarning(this, "You can't delete yourself");
                } else {
                    if (dao.selectNotDelete(txtCodeEmployee.getText())) {
                        if (Dialog.Confirm(this, "You definitely want to delete this employee!")) {
                            Delete();
                        }
                    } else {
                        Dialog.MessageWarning(this, "Employee has joined sales and has a purchase history\nCannot be deleted");
                    }
                }
            }
        } catch (Exception e) {
            Dialog.MessageError(this, "An error occurred, please contact the IT department \nError code :" + e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rdoemployyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoemployyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoemployyeActionPerformed

    private void rdomanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomanagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomanagerActionPerformed

    private void btnLeftEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftEndActionPerformed
        // TODO add your handling code here:
        leftend();
    }//GEN-LAST:event_btnLeftEndActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
        left();
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        right();
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnRightEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightEndActionPerformed
        // TODO add your handling code here:
        rightend();
    }//GEN-LAST:event_btnRightEndActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        List<InformationUsers> in = dao.SelectByKeyword(txtSearch.getText().trim());
        fillTable(in);
        updateStatus();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void mItemInforPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemInforPhoneActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                new ManagePhone(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemInforPhoneActionPerformed

    private void mItemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemOrderActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                new ManageOrder(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemOrderActionPerformed

    private void mItemStorePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemStorePhoneActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                new StorePhone(this, true).setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemStorePhoneActionPerformed

    private void mItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemExitActionPerformed
        // TODO add your handling code here:
        if (Dialog.Confirm(this, "Are you sure you want to escape?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_mItemExitActionPerformed

    private void btnCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanelActionPerformed
        // TODO add your handling code here:
        if (Dialog.Confirm(this, "You definitely want to escape!")) {
            Login.clear();
            System.exit(0);
        }
    }//GEN-LAST:event_btnCanelActionPerformed

    private void mItemTurnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTurnoverActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(2);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_mItemTurnoverActionPerformed

    private void mItemDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDebtActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(1);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemDebtActionPerformed

    private void mitemBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemBackActionPerformed
        // TODO add your handling code here:
        if (Dialog.Confirm(this, "Are you sure you escaped?"))
            System.exit(0);
    }//GEN-LAST:event_mitemBackActionPerformed

    private void btnKPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKPIActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(0);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnKPIActionPerformed

    private void mItemKDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemKDIActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(0);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mItemKDIActionPerformed

    private void btnTurnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoverActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(2);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTurnoverActionPerformed

    private void btnDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebtActionPerformed
        // TODO add your handling code here:
        try {
            if (Login.user == null) {
                Dialog.MessageWarning(this, "Please login to use the function!");
            } else {
                StatisticalJFrame st = new StatisticalJFrame(this, true);
                st.setTab(1);
                st.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDebtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<showDetailor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</showDetailor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataBirth;
    private javax.swing.JPanel Main;
    private javax.swing.JScrollPane SPTable;
    private javax.swing.JButton btnCanel;
    private javax.swing.JButton btnDebt;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnG;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnKPI;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnLeftEnd;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnRightEnd;
    private javax.swing.JButton btnScan;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTurnover;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnmanagePhone;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFind;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblcodeEmpoloyee;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblinfor;
    private javax.swing.JLabel lblname;
    private javax.swing.JMenuItem mItemAbout;
    private javax.swing.JMenuItem mItemChangePass;
    private javax.swing.JMenuItem mItemDebt;
    private javax.swing.JMenuItem mItemExit;
    private javax.swing.JMenuItem mItemImport;
    private javax.swing.JMenuItem mItemInforCustomer;
    private javax.swing.JMenuItem mItemInforPhone;
    private javax.swing.JMenuItem mItemKDI;
    private javax.swing.JMenuItem mItemLogin;
    private javax.swing.JMenuItem mItemLogout;
    private javax.swing.JMenuItem mItemOrder;
    private javax.swing.JMenuItem mItemStorePhone;
    private javax.swing.JMenuItem mItemTurnover;
    private javax.swing.JMenuItem mItemUse;
    private javax.swing.JMenuItem mitemBack;
    private javax.swing.JMenu mnuAccout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuStatistical;
    private javax.swing.JMenu mnuView;
    private javax.swing.JMenuBar mnumanager;
    private javax.swing.JPanel panelMain;
    private javax.swing.JRadioButton rdoemployye;
    private javax.swing.JRadioButton rdomanager;
    private javax.swing.JToolBar.Separator spll;
    private javax.swing.JPopupMenu.Separator spt;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JToolBar tlbmanager;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCodeEmployee;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    void setLayout() {
        DataBirth.setUI(new BasicPanelUI());

        SPTable.setUI(new BasicScrollPaneUI());
        tlbmanager.setUI(new BasicToolBarUI());
//        mnumanager.setUI(new BasicMenuBarUI());
        Main.setUI(new BasicPanelUI());
        panelMain.setUI(new BasicPanelUI());
        spll.setUI(new BasicSeparatorUI());
        spt.setUI(new BasicSeparatorUI());
        tblEmployee.setUI(new BasicTableUI());
        tblEmployee.setBorder(new LineBorder(new Color(214, 228, 229), 2));
//        rdoemployye.setUI(new BasicRadioButtonUI());
//        rdomanager.setUI(new BasicRadioButtonUI());
        tlbmanager.setBackground(new Color(200, 223, 235));
        mnumanager.setBackground(new Color(200, 223, 235));
        panelMain.setBackground(new Color(210, 210, 210));
        Main.setBackground(new Color(210, 210, 210));
        DataBirth.setBackground(new Color(210, 210, 210));

//        SPTable.setBackground(new Color(200,200,200));
        JButton[] btns = {btnCanel, btnDelete, btnInsert, btnKPI, btnLeft, btnLeftEnd,
            btnLogout, btnReset, btnRight, btnRightEnd, btnScan, btnSearch, btnDebt,
            btnTurnover, btnUpdate, btnUpload, btnmanagePhone};
        for (JButton btn : btns) {
            btn.setUI(new BasicButtonUI());
            btn.setBackground(new Color(214, 228, 229));
            btn.setBorder(new LineBorder(new Color(239, 245, 245), 1));
            btn.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(244, 157, 26));
                    btn.setBorder(new LineBorder(new Color(240, 240, 240), 1));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(214, 228, 229));
                    btn.setBorder(new LineBorder(new Color(239, 245, 245), 1));
                }
            });
        }
        JLabel[] lbs = {image, lblAddress, lblFind, lblYear, lblcodeEmpoloyee, lblemail, lblimage, lblinfor, lblname};
        for (JLabel lb : lbs) {
            lb.setUI(new BasicLabelUI());
        }
//        JMenu[] nmus = {mnuAccout, mnuHelp, mnuManage, mnuStatistical, mnuView};
//        for (JMenu mnu : nmus) {
//            mnu.setUI(new BasicMenuUI());
//            mnu.setBackground(new Color(200, 223, 235));
//            mnu.addMouseListener(new MouseAdapter() {
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
//                    mnu.setBackground(new Color(244, 175, 26));
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    mnu.setBackground(new Color(200, 223, 235));
//                }
//            });
//        }
//        JMenuItem[] mnuIs = {mItemAbout, mItemChangePass, mItemExit, mItemImport,
//            mItemInforCustomer, mItemInforPhone, mItemKDI, mItemLogin, mItemLogout,
//            mItemOrder, mItemStorePhone, mItemTopselling, mItemTurnover, mItemUse, mitemBack};
//        for (JMenuItem mnuI : mnuIs) {
//            mnuI.setUI(new BasicMenuItemUI());
//            mnuI.setBackground(new Color(244, 175, 26));
//            mnuI.setBorder(new LineBorder(new Color(239, 245, 245), 1));
//            mnuI.addMouseListener(new MouseAdapter() {
//                @Override
//                public void mouseClicked(MouseEvent e) {
//                   mnuI.setBackground(new Color(10, 10, 10));
//                    mnuI.setBorder(new LineBorder(new Color(240, 240, 240), 1));
//                }
//
//                @Override
//                public void mousePressed(MouseEvent e) {
//                    mnuI.setBackground(new Color(10, 10, 10));
//                    mnuI.setBorder(new LineBorder(new Color(240, 240, 240), 1));
//                }
//
//                @Override
//                public void mouseReleased(MouseEvent e) {
//                 mnuI.setBackground(new Color(10, 10, 10));
//                    mnuI.setBorder(new LineBorder(new Color(240, 240, 240), 1));
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
////                    mnuI.setBackground(new Color(200, 175, 26));
//                    mnuI.setBorder(new LineBorder(new Color(240, 240, 240), 1));
//                    mnuI.setForeground(new Color(250,250,250));
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    mnuI.setBackground(new Color(244, 175, 26));
//                    mnuI.setBorder(new LineBorder(new Color(239, 245, 245), 1));
//                }
//            });

//        }
        JTextField[] txts = {
            txtAddress, txtCodeEmployee, txtEmail,
            txtFullName, txtPhoneNumber, txtSearch};
        for (JTextField txt : txts) {
            txt.setUI(new BasicTextFieldUI());
        }
    }

    void getImage() {
        JFileChooser filechoose = new JFileChooser();
        if (txtCodeEmployee.getText().trim().equals("")) {
            Dialog.MessageError(this, "Please enter CodeEmployee to choose an image");
        } else {
            if (filechoose.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = filechoose.getSelectedFile();
                XImage.SaveImgFace(file, txtCodeEmployee.getText().trim());
                ImageIcon icon = XImage.ReadImgFace(txtCodeEmployee.getText().trim() + ".jpg");
                lblimage.setIcon(XImage.setResizeable(icon, 150, 200, 0));
                lblimage.setToolTipText(txtCodeEmployee.getText().trim() + ".jpg");
            }
        }
    }

    void showDetail() {
        if (row != -1) {
            String code = String.valueOf(tblEmployee.getValueAt(row, 0));
            InformationUsers info = dao.SelectID(code);
            this.setForm(info);
            tblEmployee.setRowSelectionInterval(row, row);
            txtCodeEmployee.setRequestFocusEnabled(false);
            this.updateStatus();
        }
    }

    InformationUsers getForm() {
        InformationUsers cd = new InformationUsers();
        cd.setUserName(txtCodeEmployee.getText().trim());
        cd.setPassWords("1234");
        cd.setAddress(txtAddress.getText());
        cd.setBirthYear(DataBirth.getDate());
        cd.setEmail(txtEmail.getText());
        cd.setName(txtFullName.getText());
        cd.setPhoneNumber(txtPhoneNumber.getText());
        cd.setImage(lblimage.getToolTipText() == null ? "No Image" : lblimage.getToolTipText());
        cd.setRoles(rdomanager.isSelected() ? true : false);
        return cd;
    }

    void setForm(InformationUsers cd) {
        txtCodeEmployee.setText(cd.getUserName());
        txtAddress.setText(cd.getAddress());
        txtEmail.setText(cd.getEmail());
        txtFullName.setText(cd.getName());
        txtPhoneNumber.setText(cd.getPhoneNumber());
        DataBirth.setDate(cd.getBirthYear());
        if (cd.isRoles() == true) {
            rdomanager.setSelected(true);
        } else {
            rdoemployye.setSelected(true);
        }
        if (cd.getImage() != null && !cd.getImage().equals("No Image")) {
            lblimage.setToolTipText(cd.getImage());
            ImageIcon icon = XImage.ReadImgFace(cd.getImage());
            lblimage.setIcon(XImage.setResizeable(icon, 150, 200, 0));
        } else {
            lblimage.setToolTipText(null);
            lblimage.setIcon(null);
        }
    }

    void Insert() {
        InformationUsers cd = getForm();;
        try {
            int check = dao.InsertReturn(cd);
            this.fillTable();
            this.clearForm();
            if (check > 0) {
                Dialog.Message(this, "Successfully added new");
            } else {
                Dialog.Message(this, "No items added");
            }
        } catch (Exception e) {
            Dialog.Message(this, "This employee already exists, can't add a new one");
        }

    }

    void Update() {
        InformationUsers cd = getForm();
        try {
            int check = dao.UpdateReturn(cd);
            this.fillTable();
            if (check > 0) {
                Dialog.Message(this, "Update successful");
            } else {
                Dialog.Message(this, "No items have been updated");
            }
        } catch (Exception e) {
            Dialog.Message(this, "Update failed");
        }

    }

    void Delete() {
        String manv = txtCodeEmployee.getText().trim();
        if (Dialog.Confirm(this, "Do you really want to delete this employee?")) {
            try {
                int check = dao.DeteleReturn(manv);
                this.fillTable();
                this.clearForm();
                if (check > 0) {
                    Dialog.Message(this, "Delete successfully");
                } else {
                    Dialog.Message(this, "No employees have been deleted");
                }
            } catch (Exception e) {
                Dialog.Message(this, "Error occurred, delete failed");
            }
        }
    }

    public void clearForm() {
        txtAddress.setText("");
        txtCodeEmployee.setText("");
        txtEmail.setText("");
        txtFullName.setText("");
        txtPhoneNumber.setText("");
        txtSearch.setText("");
        DataBirth.setDate(null);
        lblimage.setIcon(null);
        lblimage.setToolTipText(null);
        txtCodeEmployee.setRequestFocusEnabled(true);
        txtCodeEmployee.setEnabled(true);
        this.fillTable();
        this.row = -1;
        this.updateStatus();
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        try {
            List<InformationUsers> lst = dao.SelectAll();
            for (InformationUsers cd : lst) {
                Object[] row = {cd.getUserName(), cd.getName(), XDate.toString(cd.getBirthYear(), "dd/MM/yyyy"), cd.getPhoneNumber(), cd.getEmail(), cd.getAddress()};
                model.addRow(row);
            }
            tblEmployee.setDefaultEditor(Object.class,
                    null);
        } catch (Exception e) {
            Dialog.Message(this, "Unable to query data !");
        }
    }

    void fillTable(List<InformationUsers> in) {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        try {
            for (InformationUsers cd : in) {
                Object[] row = {cd.getUserName(), cd.getName(), XDate.toString(cd.getBirthYear(), "dd/MM/yyyy"), cd.getPhoneNumber(), cd.getEmail(), cd.getAddress()};
                model.addRow(row);
            }
            tblEmployee.setDefaultEditor(Object.class,
                    null);
        } catch (Exception e) {
            Dialog.Message(this, "Unable to query data !");
        }
    }

    void rightend() {
        this.row = tblEmployee.getRowCount() - 1;
        this.showDetail();
    }

    void leftend() {
        this.row = 0;
        this.showDetail();
    }

    void right() {
        if (this.row < tblEmployee.getRowCount() - 1) {
            this.row++;
            this.showDetail();
        }
    }

    void left() {
        if (this.row > 0) {
            this.row--;
            this.showDetail();
        }
    }

    void updateStatus() {
        boolean showDetail = (this.row >= 0);
        boolean leftend = (this.row == 0);
        boolean rightend = (this.row == tblEmployee.getRowCount() - 1);
        //trang thai from
        btnInsert.setEnabled(!showDetail);
        btnUpdate.setEnabled(showDetail);
        btnDelete.setEnabled(showDetail);
        //nut chuyen tiep
        btnLeft.setEnabled(showDetail && !leftend);
        btnLeftEnd.setEnabled(showDetail && !leftend);
        btnRight.setEnabled(showDetail && !rightend);
        btnRightEnd.setEnabled(showDetail && !rightend);
    }
}
