/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFarme;

import javax.swing.ImageIcon;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Entity.InformationPhone;
import Libraries.XDate;
import DAO.ImportCouponDAO;
import DAO.InformationPhoneDAO;
import Entity.ImportCoupon;
import Libraries.Dialog;
import Libraries.Login;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ManageImport extends javax.swing.JDialog {

    /**
     * Creates new form ImportCoupon
     */
    public int row;
    public int crurrcetImport = 0;

    public ManageImport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelnen = new javax.swing.JPanel();
        lbCodephone = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        cboCodePhone = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        lbNote = new javax.swing.JLabel();
        thanhtruotnote = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        thanhtruottable = new javax.swing.JScrollPane();
        tblImportCoupon = new javax.swing.JTable();
        btnNewProduct = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbImport = new javax.swing.JLabel();
        txtDateImport = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Import Coupon");
        setIconImage(new ImageIcon(getClass().getResource("/Image/Icon/Logo.jpg")).getImage());

        Panelnen.setBackground(new java.awt.Color(204, 255, 204));

        lbCodephone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lbCodephone.setText("Code Phone:");

        lbQuantity.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lbQuantity.setText("Quantity:");

        lbDate.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lbDate.setText("Date Import:");

        cboCodePhone.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        cboCodePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodePhoneActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lbNote.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lbNote.setText("Note:");

        txtNote.setColumns(20);
        txtNote.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtNote.setRows(5);
        thanhtruotnote.setViewportView(txtNote);

        tblImportCoupon.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        tblImportCoupon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Import", "Code Phone", "Name Phone", "Quantity", "Data Import", "Name Employe"
            }
        ));
        tblImportCoupon.setRowHeight(20);
        tblImportCoupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblImportCouponMouseReleased(evt);
            }
        });
        thanhtruottable.setViewportView(tblImportCoupon);

        btnNewProduct.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/New.png"))); // NOI18N
        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/insert.png"))); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Reset.png"))); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Cancel_1.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbImport.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lbImport.setForeground(new java.awt.Color(255, 153, 0));
        lbImport.setText("Import Coupon");

        txtDateImport.setBackground(new java.awt.Color(204, 255, 204));
        txtDateImport.setDateFormatString("dd/MM/yyyy");
        txtDateImport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelnenLayout = new javax.swing.GroupLayout(Panelnen);
        Panelnen.setLayout(PanelnenLayout);
        PanelnenLayout.setHorizontalGroup(
            PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelnenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelnenLayout.createSequentialGroup()
                        .addComponent(lbImport)
                        .addGap(50, 50, 50))
                    .addGroup(PanelnenLayout.createSequentialGroup()
                        .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(thanhtruottable, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelnenLayout.createSequentialGroup()
                                    .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbCodephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cboCodePhone, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDateImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(30, 30, 30)
                                    .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNote)
                                        .addComponent(thanhtruotnote, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelnenLayout.createSequentialGroup()
                                .addComponent(btnNewProduct)
                                .addGap(50, 50, 50)
                                .addComponent(btnInsert)
                                .addGap(218, 218, 218)
                                .addComponent(btnDelete)
                                .addGap(50, 50, 50)
                                .addComponent(jButton6)
                                .addGap(50, 50, 50)
                                .addComponent(btnCancel)))
                        .addGap(20, 20, 20))))
            .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelnenLayout.createSequentialGroup()
                    .addGap(364, 364, 364)
                    .addComponent(btnUpdate)
                    .addContainerGap(526, Short.MAX_VALUE)))
        );
        PanelnenLayout.setVerticalGroup(
            PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelnenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbImport)
                .addGap(18, 18, 18)
                .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelnenLayout.createSequentialGroup()
                        .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodephone)
                            .addComponent(cboCodePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNote))
                        .addGap(30, 30, 30)
                        .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDate)
                            .addComponent(txtDateImport, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(thanhtruotnote, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(thanhtruottable, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(PanelnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelnenLayout.createSequentialGroup()
                    .addGap(443, 443, 443)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panelnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void cboCodePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodePhoneActionPerformed
//        selectPhoneCode();
    }//GEN-LAST:event_cboCodePhoneActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblImportCouponMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImportCouponMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblImportCoupon.getSelectedRow();
            this.crurrcetImport = (int) tblImportCoupon.getValueAt(this.row, 0);
            ImportCoupon model = couponDAO.SelectID(crurrcetImport);
            this.setForm(model);
        }
    }//GEN-LAST:event_tblImportCouponMouseReleased

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // TODO add your handling code here:
        try {
            new ManagePhone(this, true).setVisible(true);
        } catch (Exception e) {
            Dialog.MessageError(this, "Unachievable");
        }
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
        } catch (Exception e) {
            Dialog.MessageError(this, "Unachievable");
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageImport dialog = new ManageImport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelnen;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboCodePhone;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel lbCodephone;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbImport;
    private javax.swing.JLabel lbNote;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JTable tblImportCoupon;
    private javax.swing.JScrollPane thanhtruotnote;
    private javax.swing.JScrollPane thanhtruottable;
    private com.toedter.calendar.JDateChooser txtDateImport;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
     InformationPhoneDAO pdao = new InformationPhoneDAO();
    ImportCouponDAO couponDAO = new ImportCouponDAO();

    private void init() {
        this.setLocationRelativeTo(null);
        this.fillComboBox();
        this.fillTabel();
        row = -1;
        this.updateStatus();

    }

    void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCodePhone.getModel();
        model.removeAllElements();
        List<InformationPhone> list = pdao.SelectAll();
        model.addElement(null);
        for (InformationPhone phoneinfo : list) {
            model.addElement(phoneinfo);
        }
    }

    void fillTabel() {
        DefaultTableModel model = (DefaultTableModel) tblImportCoupon.getModel();
        model.setRowCount(0);
        try {
            ArrayList<ImportCoupon> list = new ArrayList<ImportCoupon>();

            list = couponDAO.SelectAll();
            for (ImportCoupon coupon : list) {
                Object[] row = {
                    coupon.getCodeCoupon(),
                    coupon.getCodePhone(),
                    pdao.SelectID(coupon.getCodePhone()).getNamePhone(),
                    coupon.getQuantity(),
                    XDate.toString(coupon.getDateImport(), "dd/MM/yyyy"),
                    coupon.getCodeEmployee(),};
                model.addRow(row);
            }
            tblImportCoupon.setDefaultEditor(Object.class, null);
            this.crurrcetImport = 0;
        } catch (Exception e) {
            System.out.println(e);
        }
    }
//
//    void selectPhoneCode() {
//
//        InformationPhone phone = (InformationPhone) cboCodePhone.getSelectedItem();
//        if (phone != null) {
//            txtNote.setText("Name phone : " + phone.getNamePhone());
//        }
//        fillTabel();
//    }
    InformationPhoneDAO daoPhone = new InformationPhoneDAO();

    void insert() {
        ImportCoupon model = getForm();
        if (model != null) {
            model.setDateImport(new Date());
            try {
                couponDAO.Insert(model);
                daoPhone.UpdateSL(model.getCodePhone(), model.getQuantity());
                this.fillTabel();
                this.clear();
                Dialog.MessageInformation(this, "Insert successfull");
            } catch (Exception e) {
                System.out.println(e);
                Dialog.MessageError(this, "Insert failed");
            }
        }

    }

    void delete() {
        if (Dialog.Confirm(this, "Do you want to delete this coupon?")) {
            try {
                if (this.crurrcetImport != 0) {
                    couponDAO.Detele(this.crurrcetImport);
                     Dialog.MessageInformation(this, "Delete successfull");
                    this.fillTabel();
                    this.clear();
                } else {
                    Dialog.MessageError(this, "Bạn chưa chọn phiếu nhập");
                }
            } catch (Exception e) {
                Dialog.MessageError(this, "Delete failed");
            }
        }
    }

    void update() {
        ImportCoupon model = getForm();
        try {
            if (model != null) {
                couponDAO.Update(model);
                Dialog.MessageInformation(this, "Update successfull");
                this.fillTabel();
            }
        } catch (Exception e) {
            Dialog.MessageError(this, "Update faild");
        }
    }

    void clear() {
        cboCodePhone.setSelectedIndex(0);
        txtQuantity.setText("");
        txtNote.setText("");
        txtDateImport.setDate(null);
        this.row = -1;
        fillTabel();
        this.updateStatus();
    }

    void setForm(ImportCoupon model) {
        DefaultComboBoxModel mod = (DefaultComboBoxModel) cboCodePhone.getModel();
        InformationPhone p = pdao.SelectID(model.getCodePhone());
        mod.setSelectedItem(p);
        txtDateImport.setDate(model.getDateImport());
        txtQuantity.setText(String.valueOf(model.getQuantity()));
        txtNote.setText(model.getNote());
        this.updateStatus();
    }

//    int indexTable(Object ob) {
//        int count = tblImportCoupon.getRowCount();
//        for (int i = 0; i < count; i++) {
//            if (tblImportCoupon.getValueAt(row, 0) == ob) {
//                return i;
//            }
//        }
//        return -1;
//    }
    ImportCoupon getForm() {
        ImportCoupon model = new ImportCoupon();
        InformationPhone phone = (InformationPhone) cboCodePhone.getSelectedItem();
        if (phone == null) {
            Dialog.MessageWarning(null, "Please select codephone");
            return null;
        } else {
            model.setCodePhone(phone.getCodePhone());
            model.setQuantity(Integer.parseInt(txtQuantity.getText()));
            if (txtDateImport.getDate() != null) {
                model.setDateImport(txtDateImport.getDate());
            }
            try {
                model.setCodeEmployee(Login.user.getUserName());
            } catch (Exception e) {
                Dialog.MessageError(this, "Not logged in yet");
            }
            // model.setCodeEmployee("nhanvienkithuat");
            model.setNote(txtNote.getText());
            model.setCodeCoupon(this.crurrcetImport);
            return model;
        }
    }

    void updateStatus() {
        boolean showDetail = (this.row >= 0);
        //trang thai from
        btnInsert.setEnabled(!showDetail);
        btnUpdate.setEnabled(showDetail);
        btnDelete.setEnabled(showDetail);
        //nut chuyen tiep
    }
}
